name: Rust
on: push
env:
  CARGO_TERM_COLOR: always
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install stable toolchain
      uses: dtolnay/rust-toolchain@stable
    - name: Format
      run: cargo fmt --all -- --check
    - name: Lint
      run: cargo clippy -- -D warnings
    - name: Build
      run: cargo build --verbose --locked --release --target ${{ matrix.target }}
    - name: Tests
      run: cargo test --all-features --locked
